

services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "5001:5000"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "8001:8001"
    dns:
      - 8.8.8.8
