

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"
    
    env_file:
      - ./backend/.env

  # No mongo service needed as you use Atlas
