version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
    environment:
      - VITE_API_URL=http://backend:5000  # Set backend service as the API URL
    ports:
      - "5173:5173"  # Host:Container (Frontend will run on 5173)
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"  # Host:Container (Backend will run on 5000)
    env_file:
      - ./Backend/.env
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  app-network:
    driver: bridge
