services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "5001:5000"  # Host:Container
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "8001:80"  # Host:Container (updated to expose internal port 80)
    dns:
      - 8.8.8.8
